apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auto-deploy-apps-test-1
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.5.2
    helm:
      releaseName: ingress-nginx-1
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated: {}
